In [140]:
import torch
import numpy as np

In [3]:
print(torch.__version__)

2.10.0+cpu


In [5]:
if torch.cuda.is_available():
    print('Gpu is available')
else:
    print('Gpu is not available')

Gpu is not available


##### Creating a tensor

In [9]:
# using empty
a = torch.empty(size=(2,3))

In [10]:
type(a)

torch.Tensor

In [11]:
# using zeros
torch.zeros(size = (2,3))

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [12]:
# using ones
torch.ones(size=(2,3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [14]:
# using random
torch.rand(size = (2,3))

tensor([[0.4143, 0.8770, 0.5622],
        [0.8025, 0.6839, 0.3474]])

In [16]:
# manual seed
torch.manual_seed(100)
torch.rand(size = (2,3))

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [22]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

In [27]:
torch.arange(1,11,1).reshape(5,2)

tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]])

In [ ]:
# using linspace
torch.linspace(1,100,100).reshape(10,10)

tensor([[  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.],
        [ 11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.],
        [ 21.,  22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.],
        [ 31.,  32.,  33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.],
        [ 41.,  42.,  43.,  44.,  45.,  46.,  47.,  48.,  49.,  50.],
        [ 51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.,  60.],
        [ 61.,  62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,  70.],
        [ 71.,  72.,  73.,  74.,  75.,  76.,  77.,  78.,  79.,  80.],
        [ 81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,  89.,  90.],
        [ 91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99., 100.]])

In [34]:
# using eye
torch.eye((5)) # identity matrix

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [35]:
# using full
torch.full((3,3),5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

##### Tensor shapes

In [44]:
x = torch.full((10,10,10),69)
x.shape

torch.Size([10, 10, 10])

In [45]:
a = torch.empty_like(x) # create an empty tensor of shape x

In [47]:
a.dtype

torch.int64

In [48]:
b = torch.full((5,5),10,dtype=torch.int64)

In [49]:
b

tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]])

In [53]:
#using to
b.to(torch.float32)

tensor([[10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.]])

##### Mathematical Operations

In [54]:
torch.full((3,3),10) + 2

tensor([[12, 12, 12],
        [12, 12, 12],
        [12, 12, 12]])

In [55]:
torch.full((3,3),10) - 2

tensor([[8, 8, 8],
        [8, 8, 8],
        [8, 8, 8]])

In [56]:
torch.full((3,3),10) * 2

tensor([[20, 20, 20],
        [20, 20, 20],
        [20, 20, 20]])

In [58]:
torch.full((3,3),11) / 2

tensor([[5.5000, 5.5000, 5.5000],
        [5.5000, 5.5000, 5.5000],
        [5.5000, 5.5000, 5.5000]])

In [59]:
torch.full((3,3),11) // 2

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

In [60]:
torch.full((3,3),10) ** 2

tensor([[100, 100, 100],
        [100, 100, 100],
        [100, 100, 100]])

##### Element wise operations

In [63]:
a = torch.full((3,3),5)
b = torch.full((3,3),10)

In [64]:
a + b

tensor([[15, 15, 15],
        [15, 15, 15],
        [15, 15, 15]])

In [65]:
a - b

tensor([[-5, -5, -5],
        [-5, -5, -5],
        [-5, -5, -5]])

In [66]:
a / b

tensor([[0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000]])

In [67]:
a // b

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [68]:
a % b

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

In [70]:
c = torch.tensor([-1,2,-3])
torch.abs(c)

tensor([1, 2, 3])

In [72]:
d = torch.tensor([1,2,3,4])
torch.negative(d)

tensor([-1, -2, -3, -4])

In [73]:
# clamp
torch.clamp(d,min=2,max=3)

tensor([2, 2, 3, 3])

##### Reduction operations

In [79]:
torch.sum(a,axis=1),torch.sum(a,axis=0),torch.sum(a)

(tensor([15, 15, 15]), tensor([15, 15, 15]), tensor(45))

In [80]:
torch.min(a,axis=1),torch.min(a,axis=0),torch.min(a)

(torch.return_types.min(
 values=tensor([5, 5, 5]),
 indices=tensor([0, 0, 0])),
 torch.return_types.min(
 values=tensor([5, 5, 5]),
 indices=tensor([0, 0, 0])),
 tensor(5))

In [81]:
torch.prod(a)

tensor(1953125)

In [83]:
torch.argmax(a)

tensor(0)

##### Mattrix operations

In [90]:
x = torch.full((3,4),5)
y = torch.full((4,4),3)

In [91]:
torch.matmul(x,y)

tensor([[60, 60, 60, 60],
        [60, 60, 60, 60],
        [60, 60, 60, 60]])

In [97]:
# dot product
x = torch.full((1,4),5).reshape(-1)
y = torch.full((1,4),3).reshape(-1)
torch.dot(x,y)

tensor(60)

In [99]:
# transpose
torch.transpose(a,0,1)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

In [101]:
# determinant
torch.det(a.to(torch.float32))

tensor(0.)

In [103]:
#inverse
x = torch.rand(4,4)
torch.inverse(x)

tensor([[-1.7212, -5.7117,  4.0877,  1.9533],
        [-9.6036, -7.6660,  7.0838,  2.1997],
        [ 7.6306,  7.1987, -5.1476, -3.2481],
        [ 2.3397,  2.8066, -2.5958,  0.5792]])

##### Special functions

In [104]:
torch.log(x)

tensor([[-1.3368e+00, -3.1503e+00, -1.5701e+00, -2.1368e+00],
        [-2.1062e+00, -3.0707e-01, -3.4001e-01, -2.3879e-01],
        [-8.7154e-01, -1.0379e-01, -3.1185e-03, -2.7903e-01],
        [-1.4966e+00, -1.1962e+00, -1.7236e+00, -1.9377e-01]])

In [105]:
torch.exp(x)

tensor([[1.3004, 1.0438, 1.2312, 1.1253],
        [1.1294, 2.0867, 2.0376, 2.1981],
        [1.5194, 2.4631, 2.7098, 2.1308],
        [1.2509, 1.3530, 1.1953, 2.2792]])

In [106]:
torch.sqrt(x)

tensor([[0.5125, 0.2070, 0.4561, 0.3436],
        [0.3488, 0.8577, 0.8437, 0.8875],
        [0.6468, 0.9494, 0.9984, 0.8698],
        [0.4732, 0.5499, 0.4224, 0.9077]])

In [107]:
torch.sigmoid(x)

tensor([[0.5653, 0.5107, 0.5518, 0.5295],
        [0.5304, 0.6760, 0.6708, 0.6873],
        [0.6031, 0.7112, 0.7304, 0.6806],
        [0.5557, 0.5750, 0.5445, 0.6951]])

In [111]:
torch.softmax(x,dim=0)

tensor([[0.2501, 0.1503, 0.1716, 0.1455],
        [0.2172, 0.3004, 0.2840, 0.2842],
        [0.2922, 0.3546, 0.3777, 0.2755],
        [0.2406, 0.1948, 0.1666, 0.2947]])

In [112]:
torch.relu(x)

tensor([[0.2627, 0.0428, 0.2080, 0.1180],
        [0.1217, 0.7356, 0.7118, 0.7876],
        [0.4183, 0.9014, 0.9969, 0.7565],
        [0.2239, 0.3023, 0.1784, 0.8238]])

##### Copying a tensor

In [115]:
a = torch.rand(3,4)

In [116]:
a

tensor([[0.5557, 0.9770, 0.4440, 0.9478],
        [0.7445, 0.4892, 0.2426, 0.7003],
        [0.5277, 0.2472, 0.7909, 0.4235]])

In [ ]:
b = a #deep copy

In [118]:
b[0][0] = 3.1416

In [119]:
b

tensor([[3.1416, 0.9770, 0.4440, 0.9478],
        [0.7445, 0.4892, 0.2426, 0.7003],
        [0.5277, 0.2472, 0.7909, 0.4235]])

In [120]:
a

tensor([[3.1416, 0.9770, 0.4440, 0.9478],
        [0.7445, 0.4892, 0.2426, 0.7003],
        [0.5277, 0.2472, 0.7909, 0.4235]])

In [125]:
id(a),id(b)

(2483159356416, 2483159356416)

In [121]:
c = a.clone()

In [122]:
c

tensor([[3.1416, 0.9770, 0.4440, 0.9478],
        [0.7445, 0.4892, 0.2426, 0.7003],
        [0.5277, 0.2472, 0.7909, 0.4235]])

In [123]:
c[0][0] = 100
c

tensor([[100.0000,   0.9770,   0.4440,   0.9478],
        [  0.7445,   0.4892,   0.2426,   0.7003],
        [  0.5277,   0.2472,   0.7909,   0.4235]])

In [124]:
a

tensor([[3.1416, 0.9770, 0.4440, 0.9478],
        [0.7445, 0.4892, 0.2426, 0.7003],
        [0.5277, 0.2472, 0.7909, 0.4235]])

In [126]:
id(a),id(c)

(2483159356416, 2483160881888)

In [128]:
device = torch.device('cuda')

In [132]:
a.flatten()

tensor([3.1416, 0.9770, 0.4440, 0.9478, 0.7445, 0.4892, 0.2426, 0.7003, 0.5277,
        0.2472, 0.7909, 0.4235])

In [137]:
# permute
a.permute(1,0)

tensor([[3.1416, 0.7445, 0.5277],
        [0.9770, 0.4892, 0.2472],
        [0.4440, 0.2426, 0.7909],
        [0.9478, 0.7003, 0.4235]])

In [139]:
# pytorch -> numpy
a = torch.tensor([1,2,3])
b = a.numpy()
type(b)

numpy.ndarray

In [141]:
# numpy ->pytorch
a = np.array([1,2,3])
b = torch.from_numpy(a)
type(b)

torch.Tensor