In [8]:
from sklearn.datasets import make_classification
import torch
from torch.utils.data import Dataset,DataLoader

In [3]:
X,y = make_classification(
    n_samples = 10,
    n_features = 2,
    n_informative = 2,
    n_redundant = 0,
    n_classes = 2,
    random_state = 42
)

In [7]:
X = torch.tensor(X,dtype=torch.float32)
y = torch.tensor(y,dtype=torch.long)

In [15]:
class CustomDataset(Dataset):
    def __init__(self,features,labels):
        self.features = features
        self.labels = labels

    def __len__(self):
        return self.features.shape[0]

    def __getitem__(self,index):
        return self.features[index], self.labels[index]

In [16]:
dataset = CustomDataset(X,y)

In [17]:
len(dataset)

10

In [18]:
dataset[5]

(tensor([-0.9382, -0.5430]), tensor(1))

In [19]:
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

In [25]:
i = 0
for batch_feature,batch_lable in dataloader:
    print("Batch:",i+1)
    print(batch_feature)
    print(batch_lable)
    print('-'*50)
    i+=1

Batch: 1
tensor([[ 1.0683, -0.9701],
        [-2.8954,  1.9769]])
tensor([1, 0])
--------------------------------------------------
Batch: 2
tensor([[ 1.8997,  0.8344],
        [-0.7206, -0.9606]])
tensor([1, 0])
--------------------------------------------------
Batch: 3
tensor([[-1.9629, -0.9923],
        [ 1.7774,  1.5116]])
tensor([0, 1])
--------------------------------------------------
Batch: 4
tensor([[ 1.7273, -1.1858],
        [-1.1402, -0.8388]])
tensor([1, 0])
--------------------------------------------------
Batch: 5
tensor([[-0.5872, -1.9717],
        [-0.9382, -0.5430]])
tensor([0, 1])
--------------------------------------------------
