In [1]:
import torch

In [2]:
torch.__version__

'2.10.0+cpu'

In [3]:
torch.cuda.is_available()

False

In [4]:
a = torch.empty(2,3)
a

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
type(a)

torch.Tensor

In [6]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
torch.rand(2,3)

tensor([[0.3264, 0.3695, 0.9010],
        [0.2000, 0.1168, 0.8393]])

In [9]:
torch.manual_seed(1)
torch.rand(2,3)

tensor([[0.7576, 0.2793, 0.4031],
        [0.7347, 0.0293, 0.7999]])

In [10]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [11]:
torch.eye(5,dtype=int)

tensor([[1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1]])

In [12]:
torch.arange(0,10).reshape(5,2)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [13]:
x= torch.linspace(1,10,50).reshape(5,10)
x

tensor([[ 1.0000,  1.1837,  1.3673,  1.5510,  1.7347,  1.9184,  2.1020,  2.2857,
          2.4694,  2.6531],
        [ 2.8367,  3.0204,  3.2041,  3.3878,  3.5714,  3.7551,  3.9388,  4.1224,
          4.3061,  4.4898],
        [ 4.6735,  4.8571,  5.0408,  5.2245,  5.4082,  5.5918,  5.7755,  5.9592,
          6.1429,  6.3265],
        [ 6.5102,  6.6939,  6.8776,  7.0612,  7.2449,  7.4286,  7.6122,  7.7959,
          7.9796,  8.1633],
        [ 8.3469,  8.5306,  8.7143,  8.8980,  9.0816,  9.2653,  9.4490,  9.6327,
          9.8163, 10.0000]])

In [14]:
x.shape

torch.Size([5, 10])

In [15]:
torch.empty_like(x)

tensor([[-1.4866e+17,  1.2822e-42,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [16]:
torch.zeros_like(x)

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [17]:
torch.ones_like(x)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [18]:
torch.manual_seed(5)
torch.rand_like(x)

tensor([[0.8303, 0.1261, 0.9075, 0.8199, 0.9201, 0.1166, 0.1644, 0.7379, 0.0333,
         0.9942],
        [0.6064, 0.5646, 0.0724, 0.6593, 0.7150, 0.5793, 0.9809, 0.6502, 0.0566,
         0.9201],
        [0.6698, 0.2615, 0.0407, 0.7850, 0.9752, 0.0903, 0.5273, 0.6794, 0.2639,
         0.3906],
        [0.1661, 0.2636, 0.0442, 0.4884, 0.7965, 0.7432, 0.9697, 0.0609, 0.4385,
         0.9868],
        [0.5819, 0.3590, 0.0497, 0.7327, 0.8796, 0.9009, 0.9186, 0.5979, 0.8564,
         0.3741]])

In [19]:
x.dtype

torch.float32

In [20]:
x.to(torch.int32)

tensor([[ 1,  1,  1,  1,  1,  1,  2,  2,  2,  2],
        [ 2,  3,  3,  3,  3,  3,  3,  4,  4,  4],
        [ 4,  4,  5,  5,  5,  5,  5,  5,  6,  6],
        [ 6,  6,  6,  7,  7,  7,  7,  7,  7,  8],
        [ 8,  8,  8,  8,  9,  9,  9,  9,  9, 10]], dtype=torch.int32)

In [21]:
torch.manual_seed(100)
a = torch.rand(2,3)
a+=2
a

tensor([[2.1117, 2.8158, 2.2626],
        [2.4839, 2.6765, 2.7539]])

In [22]:
torch.clamp(a,min=1,max=1.4)

tensor([[1.4000, 1.4000, 1.4000],
        [1.4000, 1.4000, 1.4000]])

In [35]:
b = torch.randint(size = (2,3),low = 0,high = 10, dtype=torch.float32)
b

tensor([[5., 9., 9.],
        [7., 5., 9.]])

In [46]:
torch.sum(b),torch.mean(b),torch.median(b),torch.mode(b),torch.std(b),torch.max(b),torch.min(b),torch.prod(b),torch.var(b)

(tensor(44.),
 tensor(7.3333),
 tensor(7.),
 torch.return_types.mode(
 values=tensor([9., 5.]),
 indices=tensor([2, 1])),
 tensor(1.9664),
 tensor(9.),
 tensor(5.),
 tensor(127575.),
 tensor(3.8667))

In [48]:
torch.argmax(b),torch.argmin(b)

(tensor(1), tensor(0))

In [52]:
m = torch.randint(size=(2,3),low = 0,high = 10,dtype=torch.float32)
n = torch.randint(size=(3,2),low = 0,high = 10,dtype=torch.float32)

In [53]:
torch.matmul(m,n)

tensor([[77., 18.],
        [62., 12.]])

In [57]:
torch.dot(m.reshape(-1),n.reshape(-1))

tensor(88.)

In [ ]:
torch.transpose(m,0,1)

tensor([[8., 5.],
        [3., 0.],
        [3., 6.]])

In [65]:
torch.det(torch.randint(size=(5,5),low=0,high=10,dtype=torch.float32))

tensor(10554.)

In [67]:
torch.inverse(torch.randint(size=(5,5),low=0,high=10,dtype=torch.float32))

tensor([[ 0.1593, -0.0573,  0.0786, -0.0585, -0.1136],
        [-0.0258, -0.0061, -0.0487,  0.1509,  0.0235],
        [ 0.0332, -0.4207,  0.0626,  0.2346,  0.1126],
        [-0.1560,  0.5343,  0.0387, -0.3257, -0.0481],
        [ 0.0800, -0.2190, -0.0710,  0.0477,  0.1730]])

In [68]:
m = torch.randint(size=(3,2),low = 0,high = 10,dtype=torch.float32)
n = torch.randint(size=(3,2),low = 0,high = 10,dtype=torch.float32)

In [71]:
m>n,m==n,m!=n

(tensor([[False,  True],
         [False,  True],
         [ True, False]]),
 tensor([[False, False],
         [False, False],
         [False, False]]),
 tensor([[True, True],
         [True, True],
         [True, True]]))

##### Special function

In [72]:
m = torch.randint(size=(3,2),low = 0,high = 10,dtype=torch.float32)

In [77]:
torch.log(m)

tensor([[0.6931, 1.3863],
        [1.0986, 0.6931],
        [1.0986, 0.6931]])

In [78]:
torch.exp(m)

tensor([[ 7.3891, 54.5981],
        [20.0855,  7.3891],
        [20.0855,  7.3891]])

In [79]:
torch.sqrt(m)

tensor([[1.4142, 2.0000],
        [1.7321, 1.4142],
        [1.7321, 1.4142]])

In [80]:
torch.sigmoid(m)

tensor([[0.8808, 0.9820],
        [0.9526, 0.8808],
        [0.9526, 0.8808]])

In [82]:
torch.softmax(m,dim=0)

tensor([[0.1554, 0.7870],
        [0.4223, 0.1065],
        [0.4223, 0.1065]])

In [83]:
torch.relu(m)

tensor([[2., 4.],
        [3., 2.],
        [3., 2.]])

##### Inplace operations

In [84]:
m = torch.randint(size=(3,2),low = 0,high = 10,dtype=torch.float32)
n = torch.randint(size=(3,2),low = 0,high = 10,dtype=torch.float32)
m.add_(n)

tensor([[ 2., 11.],
        [15.,  9.],
        [11.,  7.]])

##### Copying a tensor

In [85]:
m = torch.randint(size=(3,2),low = 0,high = 10,dtype=torch.float32)
n = torch.clone(m)

In [87]:
id(n)

2448081189168